<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Testriq-L17" ignored="0" name="Staging_HelpUIPageTest" tests="3" failures="1" timestamp="17 Mar 2020 08:02:22 GMT" time="30.905" errors="0">
  <testcase name="clickOnDefaultLocationAndGeostixAutomation" time="15.671" classname="com.qa.IgniteTestcases.HelpUIPageTest"/>
  <testcase name="ClickOnHelpTab" time="2.093" classname="com.qa.IgniteTestcases.HelpUIPageTest"/>
  <testcase name="VerifyRedirectedHelpTab" time="5.034" classname="com.qa.IgniteTestcases.HelpUIPageTest">
    <failure type="java.lang.AssertionError" message="expected [http://help.brandify.com/help/] but found [http://help.brandify.com/help]">
      <![CDATA[java.lang.AssertionError: expected [http://help.brandify.com/help/] but found [http://help.brandify.com/help]
at com.qa.IgnitePages.HelpUIPage.VerifyRedirectedHelpTab(HelpUIPage.java:38)
at com.qa.IgniteTestcases.HelpUIPageTest.VerifyRedirectedHelpTab(HelpUIPageTest.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- VerifyRedirectedHelpTab -->
</testsuite> <!-- Staging_HelpUIPageTest -->
